export const ADS_CONTAINER = '#movie_player > .ytp-ad-module'
export const SKIP_AD_BTN = 'button.ytp-ad-skip-button-modern'
export const CLOSE_AD_BANNER_BTN = 'button.ytp-ad-overlay-close-button'
export const MUTE_BTN = 'button.ytp-mute-button'
export const VIDEO_PLAYS_SOON_INDICATOR_TEXT = '.ytp-ad-preview-text-modern'
export const VIDEO_PLAYS_SOON_INDICATOR = '.ytp-ad-preview-container:has(.ytp-ad-text)'
